config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :users
  resources :posts do
    member do
      get :vote
      get :link_vote
    end
  end

  root 'posts#index'
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
belongs_to :user, required:false
has_many :taggings
has_many :tags, through: :taggings
end

app/models/tag.rb
class Tag < ApplicationRecord
has_many :posts
has_many :posts, :through, :tagging
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
has_many :posts
has_secure_password
end

 # validates :username, :email_address

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
    def index
      @users = User.all
    end

    def new
      @user = User.new
    end
    def current_user
      @user ||= User.find(session[:user_id]) if session[:user_id]
        
    end
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to :root
      else
        flash[:warning] = "Please fix the below."
        render :new
      end
    end

    private

    def user_params
      params.require(:user).permit(:username, :email_address, :password)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.order(vote: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new
    @post.name = params[:post][:name]
    @post.link = params[:post][:link]
    @post.summary = params[:post][:summary]
    @post.vote = 1
    @post.user= params[:post][:user]
    @post.save!
    tags= params[:post][:topic].split
    redirect_to root_path


  end

  def vote
    if current_user
    @post = Post.find(params[:id])
    @post.vote += 1
    @post.save
    redirect_to root_path
  else
    flash[:warning] = "Must be logged in."
    redirect_to :new_session
    end
  end

  def link_vote
    @post= Post.find(params[:id])
    @post.vote += 1
    @post.save
    redirect_to @post.link
  end



  def show
  end






end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action  only: [:new, :create]

    def new
      if current_user
        flash[:warning] = "Your already logged in."
        redirect_to :root
      end

    end

    def create
      user = User.find_by(
                    name: params[:session][:name]
                  )
      if user
        if user.authenticate(params[:session][:password])
          session[:user_id] = user.id
          redirect_to :root
        else
          render :new
        end
      else
        flash[:warning] = "Not a valid user."
        render :new
      end
    end

    def destroy
      session[:user_id] = nil
      flash[:success] = "Loggged out."
      redirect_to :root
    end

  end

app/controllers/sesssions_controller.rb
class SesssionsController < ApplicationController

  before_action :forbid_login, only: [:new, :create]

    def new
    end

    def create
      user = User.find_by(
                    name: params[:session][:name]
                  )
      if user
        if user.authenticate(params[:session][:password])
          session[:user_id] = user.id
          redirect_to :root
        else
          render :new
        end
      else
        flash[:warning] = "Not valid user."
        render :new
      end
    end

    def destroy
      session[:user_id] = nil
      flash[:success] = "Loggged out."
      redirect_to :root
    end

  end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  @tags = Topic.find_by(name: params[:id])


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index_users
      @user = User.all
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to root_path
      else
      flash[:warning] = "Please fill in the box."
      render :new
      end
    end

    private

    def user_params
      params.require(:user).permit(:name, :email_address, :bio, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sesssions_helper.rb
module SesssionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
  <p>
    Hello, <%= current_user.name %>
  </p>
  <%= link_to "New Post", new_post_path, class: "btn btn-primary" %>
  <%= button_to "Log out",  session_path(id: "one"), class: "btn btn-danger", method: :delete %>
<% else %>
  <%= link_to "Sign up!", :new_user %>
  <%= link_to "Log In", :new_session %>
<% end %>

<% if flash.any? %>
  <% flash.each do |key, message| %>
  <div class="alert alert-<%= key %>" role="alert">
    <p>
      <%= message %>
    </p>
  </div>
  <% end %>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= link_to "New Post", new_post_path %>
<table class="table table-striped">
  <tr>
    <th>
      Likes
    </th>
     <th>Names</th>
   </tr>
   <% @post.each do |post| %>
    <tr>

      <td>
        <%= post.vote %>
     </td>
     <td>
       <div>
         <%= link_to post.name, link_vote_post_path(post) %>
       </div>
       <div class="col-m-5">

       <%=  post.summary %>
     </div>
      </td>
      <% if current_user %>
      <td>
        <div>
          <%= link_to "Like" , vote_post_path(post), class: "col-xs-3 btn btn-default btn-xs like-button" %>
      </div>
      </td>
        <% end %>
     </tr>

     <% end %>
</table>

app/views/posts/new.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :name %>
  <%= f.input :link %>
  <%= f.input :summary %>
  <%= f.input :tags %>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<%= link_to "New User", new_post_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= simple_form_for @user do |f| %>
  <%= f.input :name %>
  <%= f.input :email_address %>
  <%= f.input :password %>
  <%= f.submit %>
<% end %>